name: Docs

on:
  push:
    branches:
      - develop
    paths:
      - 'docs/**'
      - 'CHANGELOG.md'
      - 'mkdocs.yml'

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: make dev
      - name: Setup doc deploy
        run: |
          git config --global user.name Docs deploy
          git config --global user.email docs@dummy.bot.com
      - name: Build docs website and API reference
        run: make release-docs VERSION="develop" ALIAS="stage"
      - name: Deploy all docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./api
          keep_files: true
          destination_dir: develop/api
      - name: Create redirect from old docs
        run: |
          git checkout gh-pages
          test -f 404.html && echo "Redirect already set" && exit 0
          git checkout develop -- 404.html
          git add 404.html
          git commit -m "chore: set docs redirect" --no-verify
          git push origin gh-pages -f
