name: Code quality

on:
  pull_request:
    paths:
      - "aws_lambda_powertools/**"
      - "tests/**"
      - "pyproject.toml"
      - "poetry.lock"
      - "mypy.ini"
    branches:
      - develop
      - master
  push:
    paths:
      - "aws_lambda_powertools/**"
      - "tests/**"
      - "pyproject.toml"
      - "poetry.lock"
      - "mypy.ini"
    branches:
      - develop
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: make dev
      - name: Formatting and Linting
        run: make lint
      - name: Static type checking
        run: make mypy
      - name: Test with pytest
        run: make test
      - name: Security baseline
        run: make security-baseline
      - name: Complexity baseline
        run: make complexity-baseline
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3.1.6
        with:
          file: ./coverage.xml
          # flags: unittests
          env_vars: OS,PYTHON
          name: aws-lambda-powertools-python-codecov
          # fail_ci_if_error: true  # failing more consistently making CI unreliable despite all tests above passing
          token: ${{ secrets.CODECOV_TOKEN }}
