name: Record PR number

on:
  pull_request:
    types: [opened, edited]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Save PR number
        run: |
          mkdir -p ./pr
          echo ${{ github.event.number }} > ./pr/number
          echo "${{ github.event.pull_request.title }}" > ./pr/title
          echo "${{ github.event.pull_request.body }}" > ./pr/body
          echo "${{ github.event.pull_request.user.login }}" > ./pr/author
          echo "${{ github.event.action }}" > ./pr/action
      - uses: actions/upload-artifact@v3
        with:
          name: pr
          path: pr/
